config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  root 'users#index'

  # Ресурс пользователей (экшен destroy не поддерживается)
  resources :users, except: [:destroy]

  # Ресурс сессий (только три экшена :new, :create, :destroy)
  resources :sessions, only: [:new, :create, :destroy]

  # Ресурс вопросов (кроме экшенов :show, :new, :index)
  resources :questions, except: [:show, :new, :index]

  # Синонимы путей — в дополнение к созданным в ресурсах выше.
  #
  # Для любознательных: синонимы мы добавили, чтобы показать одну вещь и потом
  # их удалим.
  get 'sign_up' => 'users#new'
  get 'log_out' => 'sessions#destroy'
  get 'log_in' => 'sessions#new'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8"/>
  <title>Хорошие вопросы</title>
  <link rel="stylesheet"
        href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
  <%= stylesheet_link_tag 'application', media: 'all' %>

  <%= csrf_meta_tags %>
</head>
<body>
<div class="header">
  <div class="container">
    <div class="header-logo">
      <h1 class="header-title"><%= link_to "Хорошие вопросы", root_path %></h1>
    </div>

    <%# Выводим в хэдере информацию для логина/авторизации/регистрации %>
    <div class="header-nav">
      <%# Если есть текущий юзер (значит он залогинен) %>
      <% if current_user %>
        <%# Даем ссылки на его профиль и на логаут %>
        <%= link_to "@#{current_user.username}", user_path(current_user) %> |
        <%= link_to 'Выйти', log_out_path %>
      <% else %>
        <%# Если нету — ссылки на регистрацию и логин %>
        <%= link_to 'Зарегистрироваться', sign_up_path,
                    class: 'button button-light button-small' %>
        <%= link_to 'Войти', log_in_path,
                    class: 'button button-light button-small' %>
      <% end %>
    </div>
  </div>
</div>

<div class="content">
  <div class="container">
    <%# Выводим сообщение об ошибке или уведомление для пользователя. %>
    <%# Если в объеккте flash есть что-то, выводим содержимое на страницу, %>
    <%# если нет, игнорируем этот блок. %>
    <% if flash.any? %>
      <div class="content-wrapper buffer-both">
        <% flash.each do |name, message| %>
          <%= content_tag :div, message, class: "flash-#{name}" %>
        <% end %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</div>
</body>
</html>